name: Build PS4PairTool

on:
  push:
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: PS4PairTool-linux-x86_64
            executable: PS4PairTool
          #- os: windows-latest
          #  artifact_name: PS4PairTool-windows-x86_64
          #  executable: PS4PairTool.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------
      # Ubuntu
      # -------------------------
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            g++ \
            libusb-1.0-0-dev \
            pkg-config

      - name: check file
        if: runner.os == 'Linux'
        run: |
          cd

      - name: Build (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          g++ -std=c++17 \
            PS4PairTool.cpp \
            -o PS4PairTool \
            $(pkg-config --cflags --libs libusb-1.0)

      # -------------------------
      # Upload artifact
      # -------------------------
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.executable }}
